"""Make location_id required for warehouses and employees

Revision ID: 326ce6b9b62d
Revises: 9b8c5d4e1a23
Create Date: 2025-11-27 21:55:00.814311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326ce6b9b62d'
down_revision = '9b8c5d4e1a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала получаем или создаем дефолтную локацию
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM locations LIMIT 1"))
    default_location = result.fetchone()
    
    if default_location:
        default_location_id = default_location[0]
    else:
        # Создаем дефолтную локацию, если нет ни одной
        connection.execute(sa.text("INSERT INTO locations (name, created_at, updated_at) VALUES ('Не указана', datetime('now'), datetime('now'))"))
        result = connection.execute(sa.text("SELECT id FROM locations WHERE name = 'Не указана'"))
        default_location_id = result.fetchone()[0]
    
    # Обновляем сотрудников без локации
    connection.execute(sa.text(f"UPDATE employees SET location_id = {default_location_id} WHERE location_id IS NULL"))
    
    # Добавляем location_id в warehouses (сначала nullable)
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
    
    # Устанавливаем дефолтную локацию для всех складов
    connection.execute(sa.text(f"UPDATE warehouses SET location_id = {default_location_id} WHERE location_id IS NULL"))
    
    # Теперь делаем location_id обязательным для warehouses
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_warehouses_location_id', 'locations', ['location_id'], ['id'])
    
    # Делаем location_id обязательным для employees
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_warehouses_location_id', type_='foreignkey')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
