"""Add telegram field to Employee

Revision ID: 84250552f030
Revises: 70aaf13c52cc
Create Date: 2025-11-26 16:42:35.674813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84250552f030'
down_revision = '70aaf13c52cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('telegram')

    # ### end Alembic commands ###
