"""Add phone and telegram fields to User

Revision ID: 87d6101e13a0
Revises: 84250552f030
Create Date: 2025-11-26 17:41:26.056595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d6101e13a0'
down_revision = '84250552f030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telegram', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telegram')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
