"""Empty placeholder migration to keep revision history consistent."""

from alembic import op

# revision identifiers, used by Alembic.
revision = "e603891f1e0e"
down_revision = "87d6101e13a0"
branch_labels = None
depends_on = None


def upgrade():
    """No-op migration (warehouse split reverted)."""
    pass


def downgrade():
    """No-op downgrade."""
    pass
"""Add Warehouse model and update Device with warehouse_id

Revision ID: e603891f1e0e
Revises: 87d6101e13a0
Create Date: 2025-11-26 17:52:18.921564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'e603891f1e0e'
down_revision = '87d6101e13a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if warehouses table exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'warehouses' not in tables:
        op.create_table('warehouses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    
    with op.batch_alter_table('devices', schema=None) as batch_op:
        # Check if warehouse_id column exists
        columns = [col['name'] for col in inspector.get_columns('devices')]
        if 'warehouse_id' not in columns:
            batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        
        # Check if location_id is already nullable
        location_col = next((col for col in inspector.get_columns('devices') if col['name'] == 'location_id'), None)
        if location_col and not location_col['nullable']:
            batch_op.alter_column('location_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        
        # Check if foreign key exists
        fks = [fk['name'] for fk in inspector.get_foreign_keys('devices')]
        if 'fk_devices_warehouse_id' not in fks:
            batch_op.create_foreign_key('fk_devices_warehouse_id', 'warehouses', ['warehouse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_devices_warehouse_id', type_='foreignkey')
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('warehouse_id')

    op.drop_table('warehouses')
    # ### end Alembic commands ###
